version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    restart: always
    image: node:12
    working_dir: /usr/src/ForDevApi
    command: bash -c "yarn install --production && yarn start:live"
    volumes:
      - ./dist/:/usr/src/ForDevApi/dist/
      - ./package.json:/usr/src/ForDevApi/package.json
    ports:
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo