version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    restart: always
    build: .
    image: for-dev-api
    command: yarn start
    volumes:
      - ./dist:/usr/src/ForDevApi/dist
    ports:
      - "3333:3333"
    links:
      - mongo